### ISSUE TITLE
Bug unicode

### ISSUE THREAD

**Issue by shakidev** [cSploit/android#499]
please change unicode windows1251 to utf-8, when i using csploit , all who connected to wifi have bug with unicode

**Comment by gainan** [comment]
hi @shakidev , I guess you mean to the MITM module. what version are you using? we've fixed recently a problem with character encoding on the [nightly](http://rootbitch.cc/csploit/cSploit-nightly.apk).
by the way, we don't set a concrete encoding, we just set it to the charset encoding of the original request.

**Comment by shakidev** [comment]
I use 1.6.2 latest version . Nightly version dont work in my phone, idk why? (Htc one m7) android 4.4.2

**Comment by shakidev** [comment]
Oh, great work nightly, i m downloaded in your link

**Comment by Cheshire1** [comment]
The problem still exist (ver. 1.6.2), nightly does not help. Mitm in nightly just does not working. This is strange.

**Comment by gainan** [comment]
Hi @Cheshire1 , can you explain us why the mitm module is not working on the nightly version?
I'll need specifically the following information using the nightly version:
- the IP you are selecting as target (network, gw, a device).
- the website that is not intercepted (if that is the case), or not working (cookie not valid for example).
- mobile device you are using.
- logcat of the session while the mitm module is active.

I can assure you that it is working ;), so help us to debug it!

**Comment by Cheshire1** [comment]
I believe you) But I do not understand why nightly does not work for me. 
 * IP target - some computer in local wifi network 
 * the website - vk.com with russian language. It is intercepted, in ver. 1.6.2, but with incorrect symbols)
This log?
[log.txt](https://github.com/cSploit/android/files/40088/log.txt)

**Comment by gainan** [comment]
ok, it looks like this problem is the same than #480 (arpspoof is not launched). Thank you for reporting it @Cheshire1 , @tux-mind is analyzing it.
